#define USE_NETCDF4 
#define USE_GRIBAPI 
#undef AFWA_GRIB_CONFIGS 
#define USE_HDF4 
#define USE_HDFEOS2 
#define USE_HDF5 
#undef USE_MINPACK 
#undef RTMS 
#undef LAPACK 
#undef MKL_LAPACK 
#undef INC_WATER_PTS
#undef COUPLED
