! Custom VOD reader
#define CUSTOM_READER_NAME CustomVOD
#define CUSTOM_READER_OBSID "Custom VOD"
#define CUSTOM_READER_VARNAME "VOD"
#define CUSTOM_READER_MINVAL 0.0001
#define CUSTOM_READER_MAXVAL 4.0
#define CUSTOM_READER_QCMINVAL 0.0
#define CUSTOM_READER_QCMAXVAL 100.0
#include "CustomReaderTemplate_f90"


#undef CUSTOM_READER_NAME
#undef CUSTOM_READER_OBSID
#undef CUSTOM_READER_VARNAME
#undef CUSTOM_READER_MINVAL
#undef CUSTOM_READER_MAXVAL
#undef CUSTOM_READER_QCMINVAL
#undef CUSTOM_READER_QCMAXVAL
