! Custom LAI reader
#define CUSTOM_READER_NAME CustomLAI
#define CUSTOM_READER_OBSID "Custom LAI"
#define CUSTOM_READER_VARNAME "LAI"
#define CUSTOM_READER_MINVAL 0.0001
#define CUSTOM_READER_MAXVAL 10.0
#define CUSTOM_READER_QCMINVAL 0.0
#define CUSTOM_READER_QCMAXVAL 100.0

module CustomLAI_Mod
#include "CustomReaderTemplate_f90"
end module CustomLAI_Mod

#undef CUSTOM_READER_NAME
#undef CUSTOM_READER_OBSID
#undef CUSTOM_READER_VARNAME
#undef CUSTOM_READER_MINVAL
#undef CUSTOM_READER_MAXVAL
#undef CUSTOM_READER_QCMINVAL
#undef CUSTOM_READER_QCMAXVAL
